// Main exports
export {
  parseCommand,
  findProjectIdByName,
  addKeysToProject,
  createLokaliseClient,
  updateKeysInProject,
  deleteKeysFromProject,
  manageTranslations,
  searchKeysInProject,
} from "./mcp.js";
export { LokaliseApiClient } from "./lokalise-client.js";
export { LokaliseMCPServer } from "./mcp-server.js";

// Type exports
export type {
  ProjectData,
  LokaliseApiResponse,
  ProjectsResponse,
  Translation,
  KeyPayload,
  CreateKeysRequest,
  CreatedKey,
  CreateKeysResponse,
  Key,
  AddKeysParams,
  ParsedCommand,
  MCPToolArguments,
  MCPToolResponse,
  MCPErrorResponse,
  MCPSuccessResponse,
  Platform,
  ExistingKey,
  KeysResponse,
  UpdateKeyRequest,
  UpdateKeysRequest,
  UpdatedKey,
  UpdateKeysResponse,
  DeleteKeysRequest,
  DeleteKeysResponse,
  TranslationDetails,
  TranslationsResponse,
  UpdateTranslationRequest,
  UpdateKey,
  DeleteKey,
  ManageTranslation,
  UpdateKeysParams,
  DeleteKeysParams,
  ManageTranslationsParams,
  MCPUpdateToolArguments,
  MCPDeleteToolArguments,
  MCPTranslationToolArguments,
  SupportedLanguage,
  SearchCriteria,
  SearchResult,
  SearchResponse,
  SearchKeysParams,
  MCPSearchToolArguments,
  TranslationStatus,
} from "./types.js";

export {
  ALLOWED_PLATFORMS,
  SUPPORTED_LANGUAGES,
  TRANSLATION_STATUSES,
} from "./types.js";
